shallow_clone: true

version: '{build}'

environment:
  matrix:
    - nodejs_version: '2.0'
    - nodejs_version: '1.8.1'
    - nodejs_version: '0.12'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build: off

test_script:
  - ps: 'npm test'
  - cmd: 'npm test'
